### ISSUE TITLE
address rule tweaks in CallSignaturesPlugin

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa-rules#679]
master's thesis https://www.ru.nl/publish/pages/769526/joren_vrancken.pdf by @joren485
page 72 has some suggestions, like:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/156560/216013795-26b769b7-a1db-4d53-b2a4-bc58012b35a5.png">

code here: https://github.com/joren485/CallSignaturesPlugin
signatures: https://github.com/joren485/CallSignaturesPlugin/tree/main/CallSignaturesPlugin/signatures

**Comment by joren485** [comment]
First of all, thanks for your interest in my thesis!

I created three PRs with some potential improvements.

Some other points that are harder to address:
* Detecting indirect calls: You will most likely need mandiant/capa#771 for this.
* False positives with common constants (for example, the `SHGetFolderPath` call in 9.2.4 of my thesis): Again, you will need something like mandiant/capa#771 to detect the actual position of the argument. 
* Capa does not catch some samples that use command line programs (e.g. `reg.exe` and `sc.exe`), because `host-interaction/process/create` is not always detected (e.g. because `ShellExecute` is called indirectly). An easy solution is to remove the requirement of `host-interaction/process/create`, however this will also increase the number of false positives.

**Comment by joren485** [comment]
@williballenthin I believe I created PRs for all rule tweaks. Can this be closed or do you want/see other improvements?
